NatLibFi/melinda-ui-rest-api

src/clients/common/rest.js, src/clients/viewer/viewer.html, src/clients/viewer/viewer.js, src/viewer/viewerRoute.js
* Fetch all merge logs by correlation id
* Set logs by blob sequence
* Save them in session
* Load sequence from session with select populated by blob sequences
=> improved logs

src/clients/viewer/viewer.css, src/clients/viewer/viewer.html, src/clients/viewer/viewer.js, src/viewer/viewerRoute.js
* Fix match select css
* Update more accurate css selectors
* Change match select lable
* Add alot line endings to js
=> Minor fixes

src/clients/artikkelit/artikkelit.js
- Reverse logic for showing and hiding review fields in form
=> MUU-331 & MUU-332

src/clients/artikkelit/artikkelit.html, src/clients/artikkelit/interfaces/constants.js
- Change term 'nimi' (name) to 'nimeke' (title)
- Change term 'Julkaisun nimellä' (by publication name) to 'Nimeke' (title)
=> MUU-342 & MUU-343

package-lock.json, package.json, src/clients/common/rest.js
- Created a common function for UI for doing rest calls (fetch)
- Refactored the rest.js file so that apps use the new common rest call function
- Checked that the apps pass the user authorization token with rest call
- Updated package.json to handle a dependency vulnerability (semver)
=> MUU-155 & MUU-385

package-lock.json, src/clients/artikkelit/artikkelit.html, src/clients/artikkelit/artikkelit.js, src/clients/artikkelit/interfaces/authors.js
- Add new input field 'Yhteisön nimi' in Artikkelit form for author
- Update functions addAuthor, resetAuthor and refreshAuthorsList accordingly
- Add function 'articleAuthorRoleChange' to show or hide correct inputs and labels per author role in Article form
- Allow adding authors with only one name, if it is lastname or relator name
- Add check for names with only space in author name input fields
=> MUU-388 & MUU-391

src/clients/common/stylesheets/colors.css, src/clients/common/stylesheets/components.css, src/clients/common/stylesheets/fonts.css, src/clients/common/stylesheets/footer.css, src/clients/common/stylesheets/marc.css, src/clients/common/stylesheets/navbar.css, src/clients/common/stylesheets/progressbar.css, src/clients/keycloakLogin/keycloakLogin.css, src/clients/viewer/viewer.css
- Fixed a typo in font file name
- Added small style changes based on feedback: for example more muted colours, more space around main logo
=> MUU-454 + MUU-455 + MUU-456 + MUU-457

src/clients/muuntaja/muuntaja.html
- moved save and edit button from Muuntaja Toolbar to Tulostietue Toolbar
=> MUU-369: save and edit buttons moved to Tulostietue

src/clients/common/marc-record-ui.js, src/clients/muuntaja/muuntaja.html
Some edit field titles need to be translated to Finnish.
=> Updated translations to Finnish

src/clients/common/marc-record-ui.js
Detect different types of error messages and show user translated human readable error message instead of straight up error message. Error message itself is now error logged.
=> MUU-366: Visible error message is now a bit more generic but is translated. Specific shown in log.

src/muuntaja/config/e-to-print/defaults.js, src/muuntaja/config/print-to-e/defaults.js
The value of year is set to 008 field automatically so it wont be needed to update again once the year changes.
=> MUU-370: As requested the 008 field base value contains current year

src/clients/common/stylesheets/marc.css
There was a suggestion how to handle MUU issue with css and here it is. Css updated as suggested
=> MUU-425: As suggested updated marc record style to handle white space

src/clients/common/stylesheets/marc.css
This fixes issue ie. that appeared to edit muuntaja edit window. Fixes MUU issue and prevents the other bug.
=> MUU-425: PT2: Moved white space css setup to marc-record row. 

src/clients/muuntaja/muuntaja.html, src/clients/muuntaja/muuntaja.js
If source and base fields input has values user may press swap button. Swap button switches source and base data values in url parameters, input field values and changes transformed values around. Thus essentially switching source and base records around. This is done locally so it should not result on more back end calls.
=> Muu 364: If source and base input has ID set up enable swap button and its functionality

src/clients/common/marc-record-ui.js, src/clients/muuntaja/muuntaja.html
- detect if user made changes in edit views input:s if changes were made then enable save button and change cancel button text
- by default save button is disabled now, unless data has changed (new sub field is counted as new data but deleting same new sub field is not :) etc.
=> Muu 436: Detect if changes were made in edit view. Change info/style accordingly.

src/clients/muuntaja/muuntaja.html, src/clients/muuntaja/muuntaja.js
Clicking on the new/+ button on the toolbar empties id:s and updates the content. Effectively resetting searches.
=> MUU-361: There is a '+'/'new' button on the muuntaja toolbar

src/clients/muuntaja/muuntaja.js, src/muuntaja/config/profiles.js, src/muuntaja/muuntajaRoute.js, test-fixtures/muuntaja/special/genLOW/p2e_default/metadata.json
Use fixed profiles instead of profiles generated from user's authorization field.
=> Use fixed profiles

package-lock.json, package.json
New REST API client fixes the content of CAT tag when creating records.
=> Update newer REST API client

src/clients/common/templates/navbar.html, src/clients/login/login.html, src/clients/muuntaja/muuntaja.js, src/muuntaja/muuntajaService.js
Fixes & features:
(1) If base record is existing record, modifications are performed to that record. (2) Certain fields (001, 003, CAT) do not get ID so they are unmodifiable. (3) Removed links to not-yet-existing tools.
=> If base record is existing record, update that instead of creating a new record

src/clients/muuntaja/muuntaja.js
Transform type & profile are included to URL parameters, to create quick links to transformations.
=> Transform type & profile in URL

src/app.js, src/clients/common/navbar.js, src/clients/common/notifications/notificationConfig.json, src/clients/common/pageNotFound.js, src/clients/merge/merge.css, src/clients/merge/merge.html, src/clients/merge/merge.js
- merge client files included as slightly changed copies of muuntaja in own client folder called, merge
- navbar and pagenotfound client lists updated
- notification client list updated
- client is accessible through url
- css, html and js have some naming schemas still with muuntaja but they are within these files
- merge still uses the muuntaja route, effectively keeping base functionality intact
- I did not add link to merge to login.html homepage-services-list as its unclear should it be clearly accessible through ui yet
=> MUU-653/655/654: Base for merge client and small changes

src/clients/merge/common.js, src/clients/merge/common/common.js, src/clients/merge/common/data.js, src/clients/merge/common/dataHandler.js, src/clients/merge/common/dlgHandler.js, src/clients/merge/common/jsonHandler.js, src/clients/merge/common/transformationHandler.js, src/clients/merge/common/uiCommonHandler.js, src/clients/merge/common/uiEditHandler.js, src/clients/merge/common/urlHandler.js, src/clients/merge/merge.js, src/clients/muuntaja/muuntaja.js
Should
- cleanup
- add comments
- break down larger functions
- use modularisation
=> MUU-674: merge/muuntaja common submodules and fixes

src/muuntaja/config/baserecord/print2e.js, test-fixtures/muuntaja/general/BaseRecord/p2e_fennica/output.json
=> Muu 689: Fix 506 & 540 fields in Fennica profile
